name       : synfig
version    : 1.5.1
release    : 25
source     :
    - https://github.com/synfig/synfig/releases/download/v1.5.1/synfig-1.5.1.tar.gz : aa91593c28a89f269be1be9c8bd9ecca6491f9e6af26744d1c160c6553ee2ced
license    : GPL-3.0-or-later
component  : multimedia.library
homepage   : https://www.synfig.org/
summary    : Renderer used to convert .sif files to raster images
description: |
    Renderer used to convert synfig .sif files to raster images, videos and other formats.
builddeps  :
    - pkgconfig(ETL)
    - pkgconfig(Magick++)
    - pkgconfig(OpenEXR)
    - pkgconfig(fftw3)
    - pkgconfig(fontconfig)
    - pkgconfig(fribidi)
    - pkgconfig(glibmm-2.4)
    - pkgconfig(libavcodec)
    - pkgconfig(libjpeg)
    - pkgconfig(libxml++-2.6)
    - pkgconfig(mlt++-7)
    - libboost-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
