name       : synfig
version    : 1.2.1
release    : 4
source     :
    - https://ncu.dl.sourceforge.net/project/synfig/releases/1.2.1/source/synfig-1.2.1.tar.gz : 4d8bada4e99f05ee16b4256fc3f5a551d00a745347944837bbd6fa158b57e457
license    : GPL-3.0
component  : multimedia.library
summary    : Renderer used to convert .sif files to raster images
description: |
    Renderer used to convert synfig .sif files to raster images, videos and other formats.
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(ETL)
    - pkgconfig(fftw3)
    - pkgconfig(glibmm-2.4)
    - pkgconfig(libavcodec)
    - pkgconfig(libxml++-2.6)
    - pkgconfig(mlt++)
    - pkgconfig(OpenEXR)
    - pkgconfig(pangocairo)
    - libboost-devel
    - libjpeg-turbo-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
