name       : synfig
version    : 1.2.2
release    : 9
source     :
    - https://github.com/synfig/synfig/releases/download/v1.2.2/source-synfig-1.2.2.tar.gz : 5f5f7b33483041165f9a63fe4d95eb815971c7444569e574206f6964e83cc2ef
license    : GPL-2.0-or-later
component  : multimedia.library
summary    : Renderer used to convert .sif files to raster images
description: |
    Renderer used to convert synfig .sif files to raster images, videos and other formats.
builddeps  :
    - pkgconfig(ETL)
    - pkgconfig(OpenEXR)
    - pkgconfig(fftw3)
    - pkgconfig(glibmm-2.4)
    - pkgconfig(libavcodec)
    - pkgconfig(libjpeg)
    - pkgconfig(libxml++-2.6)
    - pkgconfig(mlt++)
    - pkgconfig(pango)
    - libboost-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
