name       : synfig
version    : 1.2.0
release    : 3
source     :
    - https://ncu.dl.sourceforge.net/project/synfig/releases/1.2.0/source/synfig-1.2.0.tar.gz : 611ea9f156188c9ecbb99a21116b5330e5070c51a0ffa721c7791c46ec231dbf
license    : GPL-3.0
component  : multimedia.library
summary    : Renderer used to convert .sif files to raster images
description: |
    Renderer used to convert synfig .sif files to raster images, videos and other formats.
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(ETL)
    - pkgconfig(fftw3)
    - pkgconfig(glibmm-2.4)
    - pkgconfig(libavcodec)
    - pkgconfig(libxml++-2.6)
    - pkgconfig(mlt++)
    - pkgconfig(OpenEXR)
    - pkgconfig(pangocairo)
    - libboost-devel
    - libjpeg-turbo-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
