name       : synfig
version    : 1.4.2
release    : 19
source     :
    - https://github.com/synfig/synfig/releases/download/v1.4.2/synfig-1.4.2.tar.gz : e66688b908ab2f05f87cc5a364f958a1351f101ccab3b3ade33a926453002f4e
license    : GPL-3.0-or-later
component  : multimedia.library
homepage   : https://www.synfig.org/
summary    : Renderer used to convert .sif files to raster images
description: |
    Renderer used to convert synfig .sif files to raster images, videos and other formats.
builddeps  :
    - pkgconfig(ETL)
    - pkgconfig(Magick++)
    - pkgconfig(OpenEXR)
    - pkgconfig(fftw3)
    - pkgconfig(glibmm-2.4)
    - pkgconfig(libavcodec)
    - pkgconfig(libjpeg)
    - pkgconfig(libxml++-2.6)
    - pkgconfig(mlt++)
    - pkgconfig(pango)
    - libboost-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
