name       : synfig
version    : 1.4.0
release    : 14
source     :
    - https://github.com/synfig/synfig/releases/download/v1.4.0/synfig-1.4.0.tar.gz : 7f36d57eba9dc959e1deae89e6908585a08db7f2d9399915a46a9eff33080c9c
license    : GPL-3.0-or-later
component  : multimedia.library
homepage   : https://www.synfig.org/
summary    : Renderer used to convert .sif files to raster images
description: |
    Renderer used to convert synfig .sif files to raster images, videos and other formats.
builddeps  :
    - pkgconfig(ETL)
    - pkgconfig(Magick++)
    - pkgconfig(OpenEXR)
    - pkgconfig(fftw3)
    - pkgconfig(glibmm-2.4)
    - pkgconfig(libavcodec)
    - pkgconfig(libjpeg)
    - pkgconfig(libxml++-2.6)
    - pkgconfig(mlt++)
    - pkgconfig(pango)
    - libboost-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
