name       : synfig
version    : 1.0.2
release    : 2
source     :
    - http://internode.dl.sourceforge.net/project/synfig/releases/1.0.2/source/synfig-1.0.2.tar.gz : 34cdf9eac90aadea29fb2997e82da1c32713ab02940f7c8873330f894e167fb4
license    : GPL-3.0
component  : multimedia.library
summary    : Renderer used to convert .sif files to raster images
description: |
    Renderer used to convert synfig .sif files to raster images, videos and other formats.
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(ETL)
    - pkgconfig(glibmm-2.4)
    - pkgconfig(libavcodec)
    - pkgconfig(libxml++-2.6)
    - pkgconfig(mlt++)
    - pkgconfig(OpenEXR)
    - pkgconfig(pangocairo)
    - libboost-devel
    - libjpeg-turbo-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
